import 'meal.dart';

class MealOption {
  final String name;
  final List<MealType> types;

  const MealOption({
    required this.name,
    required this.types,
  });

  static Iterable<String> getOptionsForType(MealType mealType) {
    return meal_options
        .where((MealOption option) => option.types.contains(mealType))
        .map((option) => option.name)
        .toList();
  }

  static const List<MealOption> meal_options = <MealOption>[
    MealOption(name: 'omlette', types: [MealType.breakfast]),
    MealOption(name: 'eggs', types: [MealType.breakfast]),
    MealOption(name: 'pb&j', types: [MealType.breakfast]),
    MealOption(name: 'avocado toast', types: [MealType.breakfast]),
    MealOption(name: 'waffles', types: [MealType.breakfast]),
    MealOption(name: 'pancakes', types: [MealType.breakfast]),
    MealOption(name: 'french toast', types: [MealType.breakfast]),
    MealOption(name: 'aloo paratha', types: [MealType.breakfast]),
    MealOption(name: 'radish paratha', types: [MealType.breakfast]),
    MealOption(name: 'paneer paratha', types: [MealType.breakfast]),
    MealOption(name: 'cereal', types: [MealType.breakfast, MealType.dinner]),
    MealOption(name: 'oatmeal', types: [MealType.breakfast]),
    MealOption(name: 'banana shake', types: [MealType.breakfast]),
    MealOption(name: 'mango shake', types: [MealType.breakfast]),
    MealOption(name: 'berry shake', types: [MealType.breakfast]),
    MealOption(name: 'masala oats', types: [MealType.breakfast]),
    MealOption(name: 'sweet dalia', types: [MealType.breakfast]),
    MealOption(name: 'savory dalia', types: [MealType.breakfast]),
    MealOption(name: 'sweet seviyan', types: [MealType.breakfast]),
    MealOption(name: 'savory seviyan', types: [MealType.breakfast]),
    MealOption(name: 'upma', types: [MealType.breakfast]),
    MealOption(name: 'besan cheela', types: [MealType.breakfast]),
    MealOption(name: 'dal cheela', types: [MealType.breakfast]),
    MealOption(name: 'oats cheela', types: [MealType.breakfast]),
    MealOption(name: 'dal parathi and halwa', types: [MealType.breakfast]),
    MealOption(name: 'macroni', types: [MealType.breakfast]),
    MealOption(name: 'mirch pakora', types: [MealType.breakfast]),
    MealOption(name: 'chole bhature', types: [MealType.breakfast]),
    MealOption(name: 'chole kulcha', types: [MealType.breakfast]),
    MealOption(name: 'bread and butter', types: [MealType.breakfast]),
    MealOption(name: 'vada pav', types: [MealType.breakfast]),
    MealOption(name: 'pasta', types: [MealType.breakfast]),
    MealOption(name: 'jawar upma', types: [MealType.breakfast]),
    MealOption(name: 'besan bread', types: [MealType.breakfast]),
    MealOption(name: 'bread pakora', types: [MealType.breakfast]),
    MealOption(name: 'bread rolls', types: [MealType.breakfast]),
    MealOption(name: 'paneer toast', types: [MealType.breakfast]),
    MealOption(name: 'aloo patties', types: [MealType.breakfast]),
    MealOption(name: 'toast mix veg', types: [MealType.breakfast]),
    MealOption(name: 'mix veg toast', types: [MealType.breakfast]),
    MealOption(name: 'aloo toast', types: [MealType.breakfast]),
    MealOption(name: 'egg toast', types: [MealType.breakfast]),
    MealOption(name: 'stuffed kulcha', types: [MealType.breakfast]),
    MealOption(name: 'matar kulcha', types: [MealType.breakfast]),
    MealOption(name: 'moong sabut and puri', types: [MealType.breakfast]),
    MealOption(name: 'moong sabut and puri', types: [MealType.breakfast]),
    MealOption(name: 'poha', types: [MealType.breakfast]),
    MealOption(name: 'bagels', types: [MealType.breakfast]),
    MealOption(name: 'cucumber sandwich', types: [MealType.breakfast]),
    MealOption(name: 'tomato sandwich', types: [MealType.breakfast]),
    MealOption(name: 'noodles', types: [MealType.lunch]),
    MealOption(name: 'salad', types: [MealType.lunch]),
    MealOption(name: 'chipotle', types: [MealType.lunch]),
    MealOption(name: '<leftover>', types: [MealType.lunch]),
    MealOption(name: 'chicken sandwich', types: [MealType.lunch]),
    MealOption(name: 'marinara pasta', types: [MealType.lunch]),
    MealOption(name: 'alfredo pasta', types: [MealType.lunch]),
    MealOption(name: 'pesto pasta', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'pizza', types: [MealType.lunch]),
    MealOption(name: 'lemon ginger chicken', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken curry', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'kadhai chicken', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'malai chicken', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken vindaloo', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken rogan josh', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'dal rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'pad thai', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'panang curry', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'drunken noodles', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'dahi chicken', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'paneer bhurji', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'shahi paneer', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'kadhai paneer', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'saag paneer', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'palak paneer', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'paneer butter masala', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'egg paratha', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'grilled cheese sandwich', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chole rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'rajma rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'aloo puri', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'salmon rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'jeera aloo', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'bhindi', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'bharta', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'arbi', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'ghia', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'aloo gobhi', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'aloo baingan', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken biryani', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'veggie biryani', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'pulav', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'stuffed dosa', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'kadhi rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'karela', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'maa chole di dal', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'khatti meethi dal', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'maggi', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'dahi kebab', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'butter chicken', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'dal makhani', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'fried rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'tacos', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'idli', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'veggie burgers', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken burgers', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'aloo burgers', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'grilled cheese sandwich', types: [MealType.breakfast, MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken kebab rice', types: [MealType.lunch, MealType.dinner]),
    MealOption(name: 'chicken gyro rice', types: [MealType.lunch, MealType.dinner])
  ];
}